# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50ee4baed89496dd555f9229e9551436e3a14fe12b1adb5944d95e8c028fd454a45106f69c27d134048f195c12f96d7b38ed8d7b962af10371a08ad4ad2f413b

test:
  secret_key_base: 8bfc9c44b1eaceac4ef90da04d28ec1d446c5ca28876670d81a6942b3dec5c35b077b927306d80f71259f75ba0ca8ce501b57ce405cd03583e241cb21c5fcf30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
